# Kinetic parameters
p = Dict([
    :sU  => 310.0,     # Source rate for protein unfolding [mol/s]
    :cB  => 0.0350,    # Attachment rate of single BiP molecule [(1/(mol^2)(1/s)]
    :gUB => 196.0,     # Dissociation rate of BiP from folding complex [(1/mol)(1/s)]
    :cD  => 0.0015,    # Enzymatic rate of disulfide bond breaking [(1/(mol^2)(1/s)] x DTT concentration [mol]
    :cE  => 0.0015,    # Enzymatic rate of disulfide bond formation [(1/(mol^2)(1/s)]
    :gB  => 0.000139,  # Decay rate of BiP [(1/mol)(1/s)]
    :gF  => 0.000833,  # Folding rate of protein in the folding complex [(1/mol)(1/s)]
    :mI  => 0.0356,    # Ire1 synthesis rate to keep the population of Ire1 approximately 256 mol [mol/s]
    :gI  => 0.000139,  # Decay rate of Ire1 (assumed the same as BiP and Ero1) [1/s]
    :cA  => 0.000233,  # Attachment rate of Ire1 molecule to an unfolded protein [(1/(mol^2)(1/s)]
    :gIB => 196.0,     # Dissociation rate of BiP from the inactive complex [(1/mol)(1/s)]
    :gIA => 196.0,     # Part of non-linear (active Ire1 cooperative) decay rate [(1/mol)(1/s)]
    :kI  => 45.0,      # Part of non-linear (active Ire1 cooperative) decay rate [mol]
    :nI  => 4.5,       # Part of non-linear (active Ire1 cooperative) decay rate
    :bHu => 0.167,     # Transcription rate of Hac1 unspliced mRNA [1/s]
    :gHs => 0.000833,  # Decay rate of Hac1 mRNA [1/s]
    :bHs => 0.0015,    # Splicing rate of Hac1 mRNA [(1/mol)(1/s)]
    :bB  => 60.9,      # BiP basal synthesis rate [mol/s]
    :nB  => 4.0,       # Part of BiP synthesis rate function
    :a0  => 296.5,     # Part of BiP synthesis rate function
    :a1  => 5.26,      # Part of BiP synthesis rate function
    :gB  => 0.000139,  # Decay rate of BiP (1/s)
    :bE  => 404.8,     # Ero1 basal synthesis rate [mol/s]
    :nE  => 7.0,       # Part of Ero1 synthesis rate function
    :gE  => 0.000139,  # Decay rate of Ero1 [1/s]
    :uT  => NaN,       # LOCAL: Constitutive I activation "boost" (to get the locally anologous system)
]);
